### ISSUE TITLE
Unable to Reproduce Paper Results

### ISSUE THREAD

**Issue by tiger28** [Alrash/TimesURL#1]
## Problem Description

I am unable to reproduce the results reported in the paper. Specifically, I have executed the following commands:

1. For dataset ETTh1:

   ```
   python train.py ETTh1 forecast --loader forecast_csv --batch-size 8 --repr-dims 320 --gpu 1 --eval
   ```

   - **Evaluation Result**:
     - **MSE (Mean Squared Error)**:
       - 24 : 0.5924
       - 48 : 0.6255
       - 168 : 0.7738
       - 336 : 0.9598
       - 720 : 1.1799
     - **MAE (Mean Absolute Error)**:
       - 24 : 0.5341
       - 48 : 0.5578
       - 168 : 0.6399
       - 336 : 0.7325
       - 720 : 0.8323
     - **Inference Time (ts2vec_infer_time)**: 1.2045 
     - **Training Time (lr_train_time)**:
       - 24 : 0.7246 
       - 48 : 0.6498 
       - 168 : 1.4347 
       - 336 : 2.3614 
       - 720 : 4.4880 
     - **Inference Time (lr_infer_time)**:
       - 24 : 0.0028 
       - 48 : 0.0032 
       - 168 : 0.0064 
       - 336 : 0.0105 
       - 720 : 0.0223 

2. For dataset ETTh2:

   ```
   python train.py ETTh2 forecast --loader forecast_csv --batch-size 8 --repr-dims 320 --gpu 1 --eval
   ```

   - **Evaluation Result**:
     - **MSE (Mean Squared Error)**:
       - 24 : 0.4032
       - 48 : 0.6102
       - 168 : 1.7924
       - 336 : 2.2721
       - 720 : 2.5625
         - **MAE (Mean Absolute Error)**:
       - 24 : 0.4834
       - 48 : 0.5892
       - 168 : 1.0224
       - 336 : 1.1781
       - 720 : 1.3049
         - **Inference Time (ts2vec_infer_time)**: 1.2382 
         - **Training Time (lr_train_time)**:
       - 24 : 0.5325 
       - 48 : 0.6714 
       - 168 : 1.4592 
       - 336 : 2.4402 
       - 720 : 4.6378 
         - **Inference Time (lr_infer_time)**:
       - 24 : 0.0028 
       - 48 : 0.0032 
       - 168 : 0.0081 
       - 336 : 0.0106 
       - 720 : 0.0230 

## Request for Assistance

I would appreciate any guidance on why I am unable to obtain the same results as reported in the paper. Are there any additional steps or considerations I should take into account?

Thank you for your help!

**Comment by RhinocerosLiu** [comment]
The experimental results in our paper are univariate time series forecasting, please use --loader forecast_csv_univar for reproducing.
